adding gradient brush
HarshKhandeparkar/gpujs-real-renderer pull request #9
Opened 2021-02-23 18:13 UTC by vivek-30

2021-02-23 18:19 UTC, HarshKhandeparkar requested changes
Small initial changes.

2021-02-23 18:19 UTC, HarshKhandeparkar commented on src/renderers/RealDrawBoard/RealDrawBoard.ts
> +  _: boolean = false; // If a tool is drawing a stroke
Is this variable even used :joy:?

2021-02-23 18:19 UTC, HarshKhandeparkar commented on src/renderers/RealDrawBoard/tools/gradientBrush.ts
> +import { type } from 'os';
I think this import is a mistake.

2021-02-23 18:19 UTC, HarshKhandeparkar commented on src/renderers/RealDrawBoard/tools/gradientBrush.ts
> +var hue: number = 0;
Let's use `let` to make it modern :smiley:

2021-02-23 18:19 UTC, HarshKhandeparkar commented on src/renderers/RealDrawBoard/tools/gradientBrush.ts
> +export const name = 'gradientBrush';
Can we name this `gradient-brush`?

2021-02-23 18:19 UTC, HarshKhandeparkar commented on src/util/convertForm.ts
> + * @param y Complex Part
Thanks, lol.

2021-02-23 18:19 UTC, HarshKhandeparkar commented on src/util/convertForm.ts
> +export function convertHSLToRGB(h: number, s: number, l: number) :[ number ,number ,number ] {
Can this be put in a separate file?

2021-02-23 19:17 UTC, vivek-30 commented on src/renderers/RealDrawBoard/RealDrawBoard.ts
> +  _: boolean = false; // If a tool is drawing a stroke
this is not created by me it is just i have seen a typo that's why i have corrected this

2021-02-23 19:17 UTC, vivek-30 commented on src/renderers/RealDrawBoard/tools/gradientBrush.ts
> +var hue: number = 0;
ok sure

2021-02-23 19:17 UTC, vivek-30 commented on src/renderers/RealDrawBoard/tools/gradientBrush.ts
> +export const name = 'gradientBrush';
sure

2021-02-23 19:18 UTC, vivek-30 commented on src/renderers/RealDrawBoard/tools/gradientBrush.ts
> +export const name = 'gradientBrush';
sure

2021-02-23 19:18 UTC, vivek-30 commented on src/util/convertForm.ts
> +export function convertHSLToRGB(h: number, s: number, l: number) :[ number ,number ,number ] {
ok please suggest a good file name

2021-02-24 03:13 UTC, vivek-30 commented on src/renderers/RealDrawBoard/tools/gradientBrush.ts
> +import { type } from 'os';
Yes .this is my mistake i will fix it😅

2021-02-24 07:36 UTC, vivek-30 commented
@HarshKhandeparkar did all the required changes please have a look on them 😊

2021-02-24 17:57 UTC, HarshKhandeparkar requested changes
Just to maintain consistency :)

2021-02-24 17:57 UTC, HarshKhandeparkar commented on src/renderers/RealDrawBoard/tools/gradient_brush.ts
> +let gradientColors: [number ,number ,number] = [ 1 ,1 ,1 ];
```suggestion
let gradientColors: [number, number, number] = [1, 1, 1]; 
```

2021-02-24 17:57 UTC, HarshKhandeparkar commented on src/renderers/RealDrawBoard/tools/gradient_brush.ts
> +  gradientColors = convertHSLToRGB(hue,90,40);
```suggestion
  gradientColors = convertHSLToRGB(hue, 90, 40);
```

2021-02-24 17:57 UTC, HarshKhandeparkar commented on src/renderers/RealDrawBoard/tools/gradient_brush.ts
> +  gradientColors = convertHSLToRGB(hue,90,40);
```suggestion
  gradientColors = convertHSLToRGB(hue, 90, 40);
```

2021-02-24 17:57 UTC, HarshKhandeparkar commented on src/renderers/RealDrawBoard/tools/gradient_brush.ts
> +  hue = (hue+1)%360;
```suggestion
  hue = (hue + 1) % 360;
```

2021-02-24 17:57 UTC, HarshKhandeparkar commented on src/renderers/RealDrawBoard/tools/gradient_brush.ts
> +  gradientColors = convertHSLToRGB(hue,90,40);
```suggestion
  gradientColors = convertHSLToRGB(hue, 90, 40);
```

2021-02-24 17:57 UTC, HarshKhandeparkar commented on src/util/convertHSLToRGB.ts
> +export function convertHSLToRGB(h: number, s: number, l: number) :[ number ,number ,number ] {
```suggestion
export function convertHSLToRGB(h: number, s: number, l: number): [number, number, number] {
```

2021-02-24 17:57 UTC, HarshKhandeparkar commented on src/util/convertHSLToRGB.ts
> +    } else if (60 <= h && h < 120) {
```suggestion
    }
    else if (60 <= h && h < 120) {
```

2021-02-24 17:57 UTC, HarshKhandeparkar commented on src/util/convertHSLToRGB.ts
> +    } else if (120 <= h && h < 180) {
```suggestion
    }
    else if (120 <= h && h < 180) {
```

2021-02-24 17:57 UTC, HarshKhandeparkar commented on src/util/convertHSLToRGB.ts
> +    } else if (180 <= h && h < 240) {
```suggestion
    }
    else if (180 <= h && h < 240) {
```

2021-02-24 17:57 UTC, HarshKhandeparkar commented on src/util/convertHSLToRGB.ts
> +    } else if (240 <= h && h < 300) {
```suggestion
    }
    else if (240 <= h && h < 300) {
```

2021-02-24 17:57 UTC, HarshKhandeparkar commented on src/util/convertHSLToRGB.ts
> +    } else if (300 <= h && h < 360) {
```suggestion
    }
    else if (300 <= h && h < 360) {
```

2021-02-24 17:57 UTC, HarshKhandeparkar commented on src/util/convertHSLToRGB.ts
> +    r = Math.round((r + m));
```suggestion
    r = Math.round(r + m);
```

2021-02-24 17:57 UTC, HarshKhandeparkar commented on src/util/convertHSLToRGB.ts
> +    g = Math.round((g + m));
```suggestion
    g = Math.round(g + m);
```

2021-02-24 17:57 UTC, HarshKhandeparkar commented on src/util/convertHSLToRGB.ts
> +    b = Math.round((b + m));
```suggestion
    b = Math.round(b + m);
```

2021-02-24 17:57 UTC, HarshKhandeparkar commented on src/util/convertHSLToRGB.ts
> +    return [ r ,g ,b ];
```suggestion
    return [r, g, b];
```

2021-02-24 18:00 UTC, HarshKhandeparkar commented
The scariest part is still left: Docs!

2021-02-25 03:38 UTC, vivek-30 commented
> The scariest part is still left: Docs!

Sorry, but i didn't get this 😅 .

2021-02-25 04:45 UTC, HarshKhandeparkar requested changes
Only line 248 in the README is left to be changed. After which, we can merge this :smiley:

2021-02-25 07:05 UTC, vivek-30 commented
@HarshKhandeparkar please have a look now ☺️

2021-02-26 18:27 UTC, vivek-30 commented
@HarshKhandeparkar please review these changes. hope you likes them 😊

2021-02-27 03:31 UTC, HarshKhandeparkar approved these changes

2021-02-27 03:33 UTC, merged

2021-02-27 03:34 UTC, HarshKhandeparkar commented
Thanks!

2021-02-27 03:37 UTC, vivek-30 commented
Welcome @HarshKhandeparkar and thanks to you as well 😊 without your help it won't be possible